// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(Props) {
  return React.createElement("div", {
              className: "text-black dark:text-white",
              id: "home"
            }, React.createElement("div", {
                  id: "top-bar"
                }, React.createElement("button", undefined), React.createElement("div", {
                      id: "top-email"
                    }), React.createElement("div", {
                      id: "socmed-links"
                    }, React.createElement("img", {
                          src: "/public/icons/iconmonstr-github-1.svg"
                        }), React.createElement("img", {
                          src: "/public/icons/iconmonstr-linkedin-3.svg"
                        }))), React.createElement("div", {
                  id: "home-title"
                }, React.createElement("div", {
                      id: "home-name"
                    }, "Kurt M. Ma. Coll"), React.createElement("div", {
                      id: "description"
                    }, "A software developer who specialises in web backend and databases")), React.createElement("div", {
                  id: "sdtc"
                }, "(Scroll down to continue.)"));
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
