// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(Props) {
  return React.createElement("div", {
              className: "skel-outline",
              id: "home"
            }, React.createElement("div", {
                  id: "home-title"
                }, React.createElement("div", {
                      id: "home-name"
                    }, "Kurt M. Ma. Coll"), React.createElement("div", {
                      id: "description"
                    }, "A software developer who specialises in web backend and databases")), React.createElement("div", {
                  id: "sdtc"
                }, "(Scroll down to continue.)"));
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
