// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(Props) {
  return React.createElement("div", {
              id: "home"
            }, "Perhaps");
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
