// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./components/Home.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

import '../styles/main.css'
;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(Home.make, {}), root);
}

export {
  
}
/*  Not a pure module */
